---

- name: Provision infrastructure
  hosts: openstack
  roles:
    - cluster_infra

- name: Configure router
  hosts: routers
  roles:
    - name: router_config
 
- hosts: private
  vars:
    router_ip_private: "{{ hostvars.localhost.terraform_provision.outputs.router_private_ip.value }}"
    squid_proxy_certificate: "{{ hostvars[cluster_name+'-router']['squid_proxy_certificate'] }}"
  tasks:
    - ansible.builtin.include_role:
        name: private_config

- hosts: localhost
  tasks:
    - debug: var=outputs
      vars:
        outputs:
          # some IP addresses here!
          private_instances: "{{ hostvars.localhost.terraform_provision.outputs.priv_floating_ips.value }}"
