---

- hosts: openstack
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:
    - stat: path="{{ config_file }}"
      register: st
    - include_vars: "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - ansible.builtin.include_role:
        name: cluster_infra

- hosts: routers
  tasks:
    - ansible.builtin.include_role:
        name: router_config
 
- hosts: private
  vars:
    router_ip_private: "{{ hostvars.localhost.terraform_provision.outputs.router_private_ip.value }}"
    squid_proxy_certificate: "{{ hostvars[cluster_name+'-router']['squid_proxy_certificate'] }}"
  tasks:
    - ansible.builtin.include_role:
        name: private_config

#- hosts: localhost
#  tasks:
#    - debug: var=outputs
#      vars:
#        outputs:
#          # some IP addresses here!
#          private_instances: ''
