---

collections:
  - name: https://github.com/stackhpc/ansible-collection-terraform
    type: git
    version: 75fb75132bbc77e3e78a05ba674458131da2b1dd
  - name: ansible.utils
    version: 2.9.0
  - name: community.crypto
    version: 2.10.0
